name: flutter_ulink_sdk
description: "Flutter SDK for creating and handling dynamic links, similar to Branch.io"
version: 0.0.1
homepage: https://github.com/mohn93/flutter_ulink_sdk

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.4.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: false
